# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pedro Silva
author: Pedro Silva
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer with a passion for technology. Over 10 years of experience in web and mobile development. Committed to open-source software and continuous learning. Let's connect and explore technology together.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pedrox.me" # the base hostname & protocol for your site, e.g. http://example.com
gravatar: e5cc524e56742b520ac89e748d329fb1
google_analytics: G-VY4R41D2VE
linkedin_username: pedro-henrique-silva

github:
  is_project_page: false

social:
  - url: https://github.com/pedrox-hs
    icon: github
  # - url: mailto:yourname@email.com
  #   icon: envelope
  # - url: https://twitter.com/username
  #   icon: twitter
  - url: https://linkedin.com/in/pedro-henrique-silva
    icon: linkedin
  - url: https://stackoverflow.com/users/4566483
    icon: stack-overflow
  - url: https://medium.com/@pedrox_
    icon: medium

header_pages:
  - about.md

# Build settings
markdown: kramdown
remote_theme: pedrox-hs/sustain
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
